version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_user_password
      - MYSQL_DATABASE=your_database
      - MYSQL_ROOT_HOST=%
    volumes:
      - "/root/project/mysql/data:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  elasticsearch:
    build: ./es
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "/root/project/es/data:/usr/share/elasticsearch/data"
      
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - "80"
      - "8080"
    volumes:
      - "/root/project/frontend/build:/usr/share/nginx/html"
      - "/root/project/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    depends_on:
      - backend
    
    
  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "6800:6800"
    expose:
      - "5000"
      - "6800"
    volumes:
      - "/root/project/backend:/home/backend"
    depends_on:
      - mysql
      - elasticsearch
    links:
      - "mysql"
      - "elasticsearch"